# Combat Timer plugin for Bukkit.
# Copyright (C) 2013 Andrew Stevanus (Hoot215) <hoot893@gmail.com>
# 
# Copying and distribution of this file, with or without modification,
# are permitted in any medium without royalty provided the copyright
# notice and this notice are preserved.  This file is offered as-is,
# without any warranty.

name: CombatTimer
main: me.hoot215.combattimer.CombatTimer
version: 1.1
author: Hoot215
